"""Constant variables used throughout the app"""

# These come from the registered app in our Spotify Developer profile
CLIENT_ID = '8aee06a9d32647a698e052031bd05312'
CLIENT_SECRET = '569e9de47a36410e93d890f39eb348d3'

# Used in Spotify API authentication calls
REDIRECT_URI = 'localhost:5000'
SECRET_KEY = '65435654345efsfdggdf'

# Generated by base64 encoding CLIENT_ID:CLIENT_SECRET
B64_CODE = 'OGFlZTA2YTlkMzI2NDdhNjk4ZTA1MjAzMWJkMDUzMTI6NTY5ZTlkZTQ3YTM2NDEwZTkzZDg5MGYzOWViMzQ4ZDM='


